# Generated by Django 5.1.2 on 2024-11-16 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_favorites'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_order', to='orders.order'),
        ),
    ]
