# Generated by Django 5.1.2 on 2024-11-16 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_current_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_order',
        ),
    ]
