# Generated by Django 5.1.2 on 2024-11-17 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_user_current_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
