# Generated by Django 5.1.2 on 2024-11-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='size',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
