# Generated by Django 5.1.2 on 2024-11-17 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartmodel_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartmodel',
            options={'verbose_name': 'Cart', 'verbose_name_plural': 'Cart'},
        ),
        migrations.AlterModelTable(
            name='cartmodel',
            table='cart',
        ),
    ]
